@baseUrl = http://localhost:3000

# MESSAGES
### Listar todas as mensagens
GET {{baseUrl}}/messages/
?limit=10
&offset=0

### Listar uma mensagem específica
GET {{baseUrl}}/messages/2

### Criar uma mensagem
POST {{baseUrl}}/messages
Content-Type: application/json

 {
    "text": "Quarta mensagem da base",
    "from": "John Doe",
    "to": "Jane Doe"
  }

### Atualizar uma mensagem
PATCH {{baseUrl}}/messages/1
Content-Type: application/json

 {
    "read": false
  }

### Remover uma mensagem
DELETE {{baseUrl}}/messages/3



# USERS
### Listar todos os usuários
GET {{baseUrl}}/users/
?limit=10
&offset=0

### Listar um usuário específico
GET {{baseUrl}}/users/9

### Criar um usuário
POST {{baseUrl}}/users
Content-Type: application/json

 {
    "name": "John Doe",
    "email": "john.doe12@example.com",
    "password": "123456"
  }

### Atualizar um usuário
PATCH {{baseUrl}}/users/9
Content-Type: application/json

 {
    "name": "John Doe da base",
    "password": "******"
  }

### Remover um usuário
DELETE {{baseUrl}}/users/4

