@baseUrl = http://localhost:3000

# MESSAGES
### Listar todas as mensagens
GET {{baseUrl}}/messages/
?limit=10
&offset=0
Authorization: Bearer Aquivemotoken

### Listar uma mensagem específica
GET {{baseUrl}}/messages/17

### Criar uma mensagem
POST {{baseUrl}}/messages
Content-Type: application/json

 {
    "text": "New message",
    "fromId": 14,
    "toId": 15
  }

### Atualizar uma mensagem
PATCH {{baseUrl}}/messages/17
Content-Type: application/json

 {
    "read": true,
    "text": "Ambos ao mesmo tempo"
  }

### Remover uma mensagem
DELETE {{baseUrl}}/messages/18

### Remover a base de mensagens
DELETE {{baseUrl}}/messages/


# USERS
### Listar todos os usuários
GET {{baseUrl}}/users/
?limit=10
&offset=0

### Listar um usuário específico
GET {{baseUrl}}/users/9

### Criar um usuário
POST {{baseUrl}}/users
Content-Type: application/json

 {
    "name": "Xereneia Teste",
    "email": "xerenei@example.com",
    "password": "123456"
  }

### Atualizar um usuário
PATCH {{baseUrl}}/users/9
Content-Type: application/json

 {
    "name": "John Doe da base",
    "password": "******"
  }

### Remover um usuário
DELETE {{baseUrl}}/users/10

### Deletar a base de usuários
DELETE {{baseUrl}}/users/
